chore(bin): update atcoder cli

diff --git a/bin/atcoder b/bin/atcoder
--- a/bin/atcoder
+++ b/bin/atcoder
@@ -5,21 +5,21 @@ set -euo pipefail
 list_contests() {
   curl -sSL "https://atcoder.jp/contests" |
     go-queryh \
-      -query "#contest-table-${contest_type} table > tbody > tr > td:nth-child(2) a" --attr href
+      -query "#contest-table-${contest_status} table > tbody > tr > td:nth-child(2) a" --attr href
 }
 
 download_contest() {
-  if [[ ! -f "${base_dir}/contests/${contest}/tasks/index.html" ]]; then
-    mkdir -p "${base_dir}/contests/${contest}/tasks"
-    curl -sSL "https://atcoder.jp/contests/${contest}/tasks" -o "${base_dir}/contests/${contest}/tasks/index.html"
-    echo "download https://atcoder.jp/contests/${contest}/tasks"
+  if [[ ! -f "${base_dir}/contests/${contest_id}/tasks/index.html" ]]; then
+    mkdir -p "${base_dir}/contests/${contest_id}/tasks"
+    curl -sSL "https://atcoder.jp/contests/${contest_id}/tasks" -o "${base_dir}/contests/${contest_id}/tasks/index.html"
+    echo "download https://atcoder.jp/contests/${contest_id}/tasks"
   else
-    echo "already downloaded https://atcoder.jp/contests/${contest}/tasks"
+    echo "already downloaded https://atcoder.jp/contests/${contest_id}/tasks"
   fi
 
   go-queryh \
     -query ".row table tbody tr td:nth-child(2)" \
-    <"${base_dir}/contests/${contest}/tasks/index.html" |
+    <"${base_dir}/contests/${contest_id}/tasks/index.html" |
     while read -r anchor; do
       href="$(echo "${anchor}" | go-queryh -query a -attr href)"
       download_contest_task "${base_dir}${href}" "https://atcoder.jp${href}"
@@ -60,24 +60,24 @@ download_contest_task() {
   done
 }
 
-test_contents_task() {
-  for no in $(seq 1 3); do
-    if [[ ! -s "${1}/test/sample-${no}.in" ]] || [[ $(wc -l <"${1}/test/sample-${no}.in") -eq 0 ]]; then
+test_contest_task() {
+  for input in $(find "${1}" -type f -name "sample-*.in" | sort -n); do
+    if [[ ! -s "${input}" ]] || [[ $(wc -l <"${input}") -eq 0 ]]; then
       return
     fi
 
-    if diff -ur <(${test_cmd[@]} <"${1}/test/sample-${no}.in") "${1}/test/sample-${no}.out"; then
-      echo "succeed test/sample-${no}.in"
+    output=${input%.in}.out
+    if diff -ur <(${test_cmd[@]} <"${input}") "${output}"; then
+      echo "succeed ${input}"
     else
-      echo "failed test/sample-${no}.in"
+      echo "failed ${input}"
     fi
   done
 }
 
 base_dir=${ATCODER_BASE_DIR:-~/src/atcoder.jp}
 test_cmd=${ATCODER_TEST_CMD:-./a.out}
-cmd=list
-contest_type=recent
+contest_status=recent
 while [[ $# -gt 0 ]]; do
   case ${1} in
   -b | --base_dir)
@@ -85,35 +85,46 @@ while [[ $# -gt 0 ]]; do
     shift
     ;;
   -c | --contest)
-    contest=${2}
+    contest_id=${2}
+    shift
+    ;;
+  -t | --task)
+    task_id=${2}
     shift
     ;;
   --upcoming)
-    contest_type=upcoming
+    contest_status=upcoming
     ;;
-  -t | --test)
-    test_cmd=(${2})
+  --test)
+    test_cmd=${2}
     shift
     ;;
-  list | download | test)
-    cmd=$1
-    ;;
-  *)
+  -*)
     echo "unsupported: $*" >&2
     exit 1
+    ;;
+  *)
+    cmd=$1
     ;;
   esac
   shift
 done
 
 case ${cmd} in
-list)
+l | list)
   list_contests
   ;;
-download)
+d | download)
   download_contest
   ;;
-test)
-  test_contents_task "$(pwd)"
+dt | download-task)
+  download_contest_task "${base_dir}/contests/${task_id}" "https://atcoder.jp/contests/${task_id}"
+  ;;
+t | test)
+  test_contest_task "$(pwd)"
+  ;;
+*)
+  echo "unsupported cmd: ${cmd}" >&2
+  exit 1
   ;;
 esac
