[bin] Throw error if input undefined option

diff --git a/.bin/clean b/.bin/clean
--- a/.bin/clean
+++ b/.bin/clean
@@ -27,7 +27,8 @@ do
       shift || break
       ;;
     *)
-      shift || break
+      echo '[ERROR] not match arguments'
+      exit 2
       ;;
   esac
 done
